num1 = int(input('Введите число №1: '))
num2 = int(input('Введите число №2: '))
print(num1, '+', num2, '=', num1+num2)
print(num1, '-', num2, '=', num1-num2)
print(num1, '*', num2, '=', num1*num2)
print(num1, '/', num2, '=', num1/num2)
print(num1, '%', num2, '=', num1%num2)